from .addsub    import *
from .branch    import *
from .loadstore import *
from .cr        import *
from .compare   import *
from .logical   import *
from .rotate    import *
from .bcd       import *
from .msr       import *
from .spr       import *
